//**********************************************************************`
//* This is an include file generated by Message Compiler.             *`
//*                                                                    *`
//* Copyright (c) Microsoft Corporation. All Rights Reserved.          *`
//**********************************************************************`
#pragma once
//+
// Provider Path of Exile Private Key Provider Event Count 1
//+
EXTERN_C __declspec(selectany) const GUID PoeKeyProvider = {0xfd3df53c, 0x5077, 0x4a8c, {0x9e, 0xe8, 0x81, 0x73, 0x88, 0x08, 0x28, 0x80}};

//
// Event Descriptors
//
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR PrivateKey = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0};
#define PrivateKey_value 0x0
